version: '3.8'
services:
  frontend-api:
    build: ./frontend-api
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  backend-worker:
    build: ./backend-worker
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
