name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_USERNAME: ghcr.io/${{ github.repository_owner }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push frontend-api Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend-api
        push: true
        tags: ${{ env.DOCKER_USERNAME }}/devops-workflow-frontend-api:${{ env.IMAGE_TAG }}

    - name: Build and push backend-worker Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend-worker
        push: true
        tags: ${{ env.DOCKER_USERNAME }}/devops-workflow-backend-worker:${{ env.IMAGE_TAG }}

    - name: Output for local deployment
      run: |
        echo "Docker images built and pushed to GitHub Container Registry."
        echo "To deploy to your local Minikube cluster, run the following commands locally:"
        echo "cd infra/terraform"
        echo "terraform init"
        echo "terraform apply -var=\"docker_username=${{ env.DOCKER_USERNAME }}\" -var=\"image_tag=${{ env.IMAGE_TAG }}\""